#!/usr/bin/env bash
# Install nginx and change the 404 page

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default

service nginx restart
