#!/usr/bin/env bash
# Install nginx and change the 404 page

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://assets.justinmind.com/wp-content/uploads/2020/04/best-404-pages.png permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
service nginx restart
