#!/usr/bin/env bash
# Install your load balancer
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 2209-web-01 54.90.162.172:80 check
    server 2209-web-02 2.90.60.120:80 check
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
