#!/usr/bin/env bash
# Login from the client to the server without password
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/holberton
    PasswordAuthentication no
	